# Generated by Django 5.2.7 on 2026-02-10 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_user_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verification_code',
        ),
    ]
