# Generated by Django 5.2.7 on 2026-02-12 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_user_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together=set(),
        ),
    ]
