# Generated by Django 5.2.7 on 2026-02-12 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_classe_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('nom', 'annee')},
        ),
    ]
