# Generated by Django 5.2.7 on 2026-02-14 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_user_github_username_user_linkedin_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='saisi_par',
            field=models.ForeignKey(limit_choices_to={'role': 'PROF'}, on_delete=django.db.models.deletion.PROTECT, related_name='notes_saisies', to=settings.AUTH_USER_MODEL),
        ),
    ]
