# Generated by Django 5.2.7 on 2026-02-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_note_saisi_par'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('PROF', 'Enseignant'), ('ETUD', 'Étudiant'), ('INV', 'Invite')], default='INV', max_length=5),
        ),
    ]
