# Generated by Django 6.0.1 on 2026-02-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_user_accepted_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='nom',
            field=models.CharField(max_length=80),
        ),
    ]
