# Generated by Django 5.2.7 on 2026-02-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_user_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
