# Generated by Django 6.0.1 on 2026-03-01 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_user_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='note',
            unique_together=set(),
        ),
    ]
